# Working with data in Python

Python is an interpreted, interactive, object-oriented programming language. 

It incorporates modules, exceptions, dynamic typing, very high level dynamic data types, and classes. 

It supports multiple programming paradigms beyond object-oriented programming, such as procedural and functional programming.

Although this is not a Python lecture, we will use Python intensively. 

So let's first get familiar with some often used data types in this lecture. Meanwhile get familiar with Jupyter Notebook.

First of all, we need to import some libraries (By now, these libraries should be included in the working environment):

In [11]:
import numpy as np
import pandas as pd


## Lists, Arrays, Series

Assume that you have the following observations of a feature: 2, 4, 6, Null, 8, and you want to assign them into one variable. There are at least three alternatives:
- Python list `ls1 = [2, 4, 6, None, 8]`
- Numpy array `arr1 = numpy.array([2, 4, 6, np.nan, 8])`
- Pandas series `s1 = pd.Series([2, 4, 6, np.nan, 8])`

*Insert a new code cell below, copy paste the above statements, and check the value of ls1, arr1 and s1.*

*To check the values, you could use* print(f"Some text here {variable here}"), or simply type the variable name in the last line of the cell)

### Python lists

Python lists might contain items of different types (also could be list of lists), but usually the items all have the same type.

It is similar to the list in JavaScript -- it has append, insert, index, ... functions. 

The next cell shows some examples.
 
More information can be found here: https://docs.python.org/3/tutorial/datastructures.html

Run the next cell, check the outputs

In [2]:
ls2 = [2, 'Sunny', 6, None, [1, 2, 3]]
print(f"Python list ls2= {ls2}")

ls2.append(199)
print(f"Updated ls2= {ls2}")

id199 = ls2.index(199)
print(f"Index of 199= {id199}")

ls234 = ls2[1:4]
print(f"The 2nd to the 4th items are {ls234}")

item_5_3 = ls2[4][2]
print(f"The 3rd item in the 5th item of ls2 is {item_5_3}")

ls10 = [1, 2, 3]
ls11 = [4, 5, 6]
ls12 = ls10 + ls11
print(f"+ works as append ls10+ls11={ls12}")

Python list ls2= [2, 'Sunny', 6, None, [1, 2, 3]]
Updated ls2= [2, 'Sunny', 6, None, [1, 2, 3], 199]
Index of 199= 5
The 2nd to the 4th items are ['Sunny', 6, None]
The 3rd item in the 5th item of ls2 is 3
+ works as append ls10+ls11=[1, 2, 3, 4, 5, 6]


The zip() function returns a zip object, which is an iterator of tuples where the first item in each passed iterator is paired together,  and then the second item in each passed iterator are paired together etc.

In [4]:
ls13 = zip(ls10, ls11)
print(f"zip(ls10, ls11)={tuple(ls13)}")

zip(ls10, ls11)=((1, 4), (2, 5), (3, 6))


Add a new cell below, and check the value of tuple(ls13), what will you get? Why? 

In [9]:
tuple(ls13)

print(ls13)

### Numpy arrays 

NumPy supports for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. --> Offer specialized functions for numerical operations with high performance.

Different from Python list, all the items in one Numpy array must have the same type/length --> consume less memory compared with lists 

https://numpy.org/doc/stable/reference/generated/numpy.array.html

#### First, let's create some arrays and retrieve some items from them.

In [12]:
d1 = np.array([1, 2, 3, 4, 5])
print(f"1D array: \n", d1, "\n")

d2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D array: \n", d2)
print('2nd item in the 1st item: ', d2[0][1])
print('Row 1, Column 2: ', d2[0, 1])
print(f"Row 3, Column 2: ", d2[2, 1], "\n")

d3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(f"3D array: \n", d3, "\n")

# Error:
#d3 = np.array([[[1, 2, 3, 100], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# Check what is the result: 
x = np.arange(12).reshape((3, 4))
display(x)
x.sum(axis=1)

1D array: 
 [1 2 3 4 5] 

2D array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2nd item in the 1st item:  2
Row 1, Column 2:  2
Row 3, Column 2:  8 

3D array: 
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([ 6, 22, 38])

#### You can operate arrays as vectors/matrices.

https://numpy.org/doc/stable/reference/routines.linalg.html

*Run the following cells, what are those calculation results?*

In [12]:
d4 = np.array([10, 10, 10, 10, 10])
d5 = d1 + d4

In [13]:
d6 = 2 * d1

In [14]:
d7 = d1 * d4

In [15]:
d8 = np.dot(d1, d4)

In [16]:
from numpy import linalg as LA

n4 = LA.norm(d4)


### Pandas series

Pandas series is a ***one-dimensional labeled*** array holding data of any type such as integers, strings, Python objects etc.
- Pandas Series is one dimensional.
- Pandas Series has an explicitly defined index associated with values.
- Pandas Series allows different data types, including objects.

https://pandas.pydata.org/docs/reference/series.html

*Run the followin cell. check the difference between s1 and any np array. Compare d1 and s2.*


In [ ]:
# One dimension
s1 = pd.Series([[1, 'a', 3], [4, 5, 6], [7, 8, 9]])
display(s1)

# You may convert an array into a Series
print(f"Original d1={d1}")
s2 = pd.Series(d1)
display(s2)

You may define the index when creating a Series `s2 = pd.Series([2, 4, 6, np.nan, 8], index=['a', 'b', 'c', 'd', 'e'])`. 

*Check the value of s2:*

In [ ]:
s2 = pd.Series([2, 4, 'Hallo', np.nan, 8], index=['a', 'b', 'c', 'd', 'e'])

You may also create Series by passing a dictionary `s3 = pd.Series(data={'a': 1, 'b': 2, 'c': 3})`

In [ ]:
s3 = pd.Series(data={'a': 1, 'b': 2, 'c': 3})

*How to retrieve value 2 of s3? How to retrieve values indexed by b, c, d of s2?*

In [ ]:
display(s3['b'])
s2['b':'d']

## DataFrame

DataFrame is a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

https://pandas.pydata.org/docs/reference/frame.html

There are various ways to initialize a dataframe. 

*Run the following cells and check the outcome.*


In [ ]:
data1 = {'Name': ["Tom", "Jerry", "Emily", "Amy"], 'Age': [18, 24, 18, 22]}
df1 = pd.DataFrame(data1)
display(df1)

In [ ]:
data2 = {'col1': [10, 11, 12, 13], 'col2': pd.Series(['A', 'B'], index=[2, 3])}

#Error:
#pd.DataFrame(data=data2)

dfWithNaA = pd.DataFrame(data=data2, index=[0, 1, 2, 3])

In [23]:
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])

#### To use Numpy functions, you can convert dataframe into array

In [ ]:
df2.to_numpy()

If there are different data types in the dataframe, they will be converted to "objects"

In [ ]:
df3 = pd.DataFrame(
    {
        "A": 1,
        "B": pd.Timestamp("20240223"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
display(df3)
df3.to_numpy()

### Overview of the datafile

With DataFrame, you can conviniently load data and have overview.

In [4]:
df = pd.read_csv("Data/advertising.csv")
display(df)

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

*Try the following commands. What are their functions?*

In [5]:
display(df.head(5))

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [6]:
display(df.tail(10))

TV  Radio  Newspaper  Sales
190   39.5   41.1        5.8   10.8
191   75.5   10.8        6.0   11.9
192   17.2    4.1       31.6    5.9
193  166.8   42.0        3.6   19.6
194  149.7   35.6        6.0   17.3
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

In [7]:
display(df.index)


RangeIndex(start=0, stop=200, step=1)

In [8]:

display(df.dtypes)


TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

In [9]:

df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

### Select data from dataframe

It is very convenient to select data from a dataframe. In addition to select by index, slicing, you can easily add conditional filters.

*How to get the data in Column TV?*

In [10]:
display(df)

print(f"Column TV: \n{df['TV']}", "\n")

print(f"Column TV: \n{df.TV}", "\n")

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

Column TV: 
0      230.1
1       44.5
2       17.2
3      151.5
4      180.8
       ...  
195     38.2
196     94.2
197    177.0
198    283.6
199    232.1
Name: TV, Length: 200, dtype: float64 

Column TV: 
0      230.1
1       44.5
2       17.2
3      151.5
4      180.8
       ...  
195     38.2
196     94.2
197    177.0
198    283.6
199    232.1
Name: TV, Length: 200, dtype: float64 


*How to get the data of Column TV and Column Newspaper?*

In [17]:
df[["TV", "Newspaper"]]

TV  Newspaper
0    230.1       69.2
1     44.5       45.1
2     17.2       69.3
3    151.5       58.5
4    180.8       58.4
..     ...        ...
195   38.2       13.8
196   94.2        8.1
197  177.0        6.4
198  283.6       66.2
199  232.1        8.7

[200 rows x 2 columns]

#### loc and iloc

- loc gets rows and/or columns with particular labels.

- iloc gets rows and/or columns at integer locations.

To test them, let's create a new dataframe with random data:

In [18]:
dates = pd.date_range('2/1/2024', periods=8)

#8-by-4 array of samples from the normal distribution
df = pd.DataFrame(np.random.randn(8, 4),
                  index=dates,
                  columns=['A', 'B', 'C', 'D'])

*Show the value of B on 4 Feb 2024*
*Hint: df.loc[row, column]*

In [22]:
df.loc["2024-02-04", "A"]

0.5360374607705775

*Show all values on 4 Feb 2024*

*Show all values of B by using df.loc[]*

*Show the values of B and C, before (including) 4 Feb 2024*

*Show the second row by using df.iloc[row, column]*

*Show the value in the second row and the second column*

*Show the first two columns of the 4th and the 5th row*

*Show all the rows which has positive B values*

*Show all the rows which has positive B values and positive A values*

*Show all the data later than 2024-02-02*

*Reminder: dates is index*

Now let's manipulte a dataframe.

*After the following operations, what is the shape of d4? (How many rows? How many collumns?)*

In [131]:
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])

df4 = df2.copy()

df4.loc[len(df4.index)] = ['A', 89, 93]

df4['type'] = ["cat", "dog", "cat", "bird"]


*Return all the data points of cats and dogs*

*Sort all the rows based on the values in Column type*